import type { Metadata } from "next";
import { Metal } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const metal = Metal({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "zxc",
  description: "Generated by zxc",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="apple-touch-icon-precomposed"
        sizes="114x114"
        type="image/svg+xml"
        href="/logo.png"
      />
      <link rel="icon" type="image/svg+xml" href="/logo.png" />
      <body className={metal.className}>
        <div className="flex h-screen text-4xl  flex-col items-center justify-between">
          <Link href="/">HEADER</Link>
          <div className="flex flex-col items-center h-[60%]">{children}</div>
          <div>FOOTER</div>
        </div>
      </body>
    </html>
  );
}
